INSERT INTO device (name, country, manufacturer, online_order, installment) VALUES
('Телевизор', 'Россия', 'Haier', true, false),
('Телевизор', 'Китай', 'Xiaomi', true, false),
('Телевизор', 'Китай', 'LG', true, true),
('Пылесос', 'Германия', 'Bosch', true, true),
('Пылесос', 'Китай', 'Starwind', false, true),
('Пылесос', 'Китай', 'Hyundai', true, false),
('Холодильник', 'Россия', 'Beko', true, false),
('Холодильник', 'Китай', 'LG', false, true),
('Холодильник', 'Болгария', 'Liebherr', true, false),
('Смартфон', 'Китай', 'Realme', true, false),
('Смартфон', 'Китай', 'Huawei', false, true),
('Смартфон', 'Китай', 'Poco', true, false),
('Компьютер', 'Китай', 'DEXP', true, true),
('Компьютер', 'Тайвань', 'Acer', true, true),
('Компьютер', 'Китай', 'MSI', true, false);